# Generated by Django 4.2.25 on 2025-11-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('activity', models.CharField(max_length=100, verbose_name='Род деятельности')),
                ('chat_link', models.URLField(verbose_name='Ссылка на чат')),
                ('group_name', models.CharField(max_length=150, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
