# Generated by Django 4.2.25 on 2025-11-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GTONormativ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('medal', models.CharField(choices=[('bronze', 'Бронза'), ('silver', 'Серебро'), ('gold', 'Золото')], max_length=10, verbose_name='Медаль')),
                ('age_group', models.CharField(max_length=50, verbose_name='Возрастная группа')),
                ('run_100m', models.CharField(blank=True, max_length=20, verbose_name='Бег 100м')),
                ('run_3km', models.CharField(blank=True, max_length=20, verbose_name='Бег 3км')),
                ('pull_ups', models.CharField(blank=True, max_length=20, verbose_name='Подтягивания')),
                ('push_ups', models.CharField(blank=True, max_length=20, verbose_name='Отжимания')),
                ('jump', models.CharField(blank=True, max_length=20, verbose_name='Прыжок в длину')),
                ('press', models.CharField(blank=True, max_length=20, verbose_name='Пресс')),
                ('flexibility', models.CharField(blank=True, max_length=20, verbose_name='Гибкость')),
            ],
        ),
    ]
