# Generated by Django 4.2.25 on 2025-11-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('inventory', models.CharField(default='', max_length=50, verbose_name='Инвентарь')),
                ('muscles', models.CharField(default='', max_length=50, verbose_name='Мышцы')),
                ('description', models.TextField(default='', max_length=250, verbose_name='Техника выполнения')),
            ],
            options={
                'verbose_name': 'Упражнения',
                'verbose_name_plural': 'Упражнения',
            },
        ),
    ]
